apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-s3-external-backup
spec:
  schedule: "0 3 * * *" # Daily at 3:00 AM UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup-to-s3
            image: rclone/rclone:latest
            args: ["sync", "--delete-after" , "/backups", "s3:mongo-db-backup/dumps", "--no-check-certificate", "--include", "mongodump-*.gz"]
            env:
              - name: RCLONE_CONFIG_S3_TYPE
                value: "s3"
              - name: RCLONE_CONFIG_S3_PROVIDER
                value: "Minio" # Change as needed for your S3-compatible provider
              - name: RCLONE_CONFIG_S3_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_ACCESS_KEY_ID
              - name: RCLONE_CONFIG_S3_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
              - name: RCLONE_CONFIG_S3_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: aws-credentials
                    key: AWS_SECRET_ACCESS_KEY
            volumeMounts:
              - name: mongodump
                mountPath: /backups
          volumes:
            - name: mongodump
              persistentVolumeClaim:
                claimName: mongo-mongodb-mongodump
          restartPolicy: OnFailure
